export const CommandIds = {
    '1-8': {
        '128th_note': '128th note',
        '16_tremolos': '16 tremolos',
        '16th_note': '16th note (semiquaver)',
        '2_tremolos': '2 tremolos',
        '256th_note': '256th note',
        '32_tremolos': '32 tremolos',
        '32nd_note': '32nd note (demisemiquaver)',
        '4_tremolos': '4 tremolos',
        '512th_note': '512th note',
        '64th_note': '64th note (hemidemisemiquaver)',
        '8_tremolos': '8 tremolos',
        '8th_note': 'Eighth note (quaver)',
    },
    a: {
        'accent': 'Accent',
        'accessibility_preferences': 'Accessibility Settings',
        'acciacatura': 'Acciaccatura',
        'add_2nd_above': 'Add interval 2nd above',
        'add_3rd_above': 'Add interval 3rd above',
        'add_4th_above': 'Add interval 4th above', 
        'add_5th_above': 'Add interval 5th above',
        'add_6th_above': 'Add interval 6th above',
        'add_7th_above': 'Add interval 7th above',
        'add_9th_above': 'Add interval 9th above',
        'add_bar_at_end': 'Bar at End',
        'add_dynamic_guitar_staff': 'Add dynamic guitar staves',
        'add_multiple_bars': 'Other Bar',
        'add_octave_above': 'Add interval an octave above',
        'add_ossia_above': 'Add Ossia Above',
        'add_ossia_below': 'Add Ossia Below',
        'add_single_bar': 'Single Bar',
        'add_stave_above': 'Add Staff Above',
        'add_stave_below': 'Add Staff Below',
        'add_unison': 'Add unison',
        'add_video': 'Add Video',
        'advance_caret': 'Advance Caret',
        'advanced_filter': 'Advanced Filter',
        'align_horizontally': 'Align in a Column',
        'align_staves': 'Align Staves',
        'align_vertically': 'Align in a Row',
        'annotate': 'Annotate',
        'append_score': 'Append Score',
        'appoggiatura': 'Appoggiatura',
        'arpeggio_down': 'Arpeggio Down',
        'arpeggio_up': 'Arpeggio Up',
        'arpeggio': 'Arpeggio',
        'arrange': 'Arrange',
        'auto_breaks': 'Auto Breaks',
    },
    b: {
        'bar_number_change': 'Bar Number Change',
        'bar_rest': 'Bar Rest',
        'barline_between_staves': 'Between Staves Barline',
        'barline_dashed': 'Dashed Barline',
        'barline_double': 'Double Barline',
        'barline_end_repeat': 'End Repeat Barline',
        'barline_final': 'Final Barline',
        'barline_invisible': 'Invisible Barline',
        'barline_normal': 'Normal Barline',
        'barline_short': 'Short Barline',
        'barline_start_repeat': 'Start Repeat Barline',
        'barline_ticks': 'Tick Barline',
        'brace': 'Brace',
        'bracket_accidental': 'Bracket accidental',
        'bracket_notehead': 'Bracket notehead',
        'bracket': 'Bracket',
        'buzz_roll': 'Buzz roll (Z on stem)',
    },
    c: {
        'calibrate_live_tempo': 'Calibrate Live Tempo',
        'cancel_stop_selectnone': 'Cancel/Stop/Select None',
        'cascade': 'Cascade',
        'change_appearance_current_part': 'Change Current Part Appearance',
        'change_appearance_of_all_parts': 'Change Appearance of AllParts',
        'change_appearance_of_open_parts': 'Change Appearance of Open Parts',
        'change_tie_style': 'Next tie style',
        'chord_diagram_toggle': 'Add/Remove Chord Diagram',
        'chord_symbols': 'Chord Symbol',
        'chord_text_root_toggle': 'Add/Remove Chord Text Root',
        'chord_text_toggle': 'Add/Remove Chord Text',
        'clear_live_tempo': 'Clear Live Tempo',
        'clef_dialog': 'Show Clef dialog',
        'clefs': 'Clef',
        'close_all': 'Close All',
        'close_tab': 'Close Tab',
        'close_window': 'Close Window',
        'color_note_none': 'Note Colors None',
        'color_note_voices': 'Voice Colors',
        'color_out_of_range_notes': 'Notes out of Range',
        'color': 'Color',
        'command_search': 'Activate Command Search',
        'comment': 'Comment',
        'compare_window': 'Compare',
        'configure_live_tempo': 'Configure Live Tempo',
        'consecutive_rehearsal_mark': 'Rehearsal Mark (consecutive)',
        'copy_and_change_instrument_in_part': 'Copy and Change Instrument',
        'copy_as_idea': 'Capture Idea',
        'copy_part_layout': 'Copy Part Layout',
        'copy': 'Copy',
        'create_highlight': 'Highlight',
        'create_hitpoint': 'Create Hit Point',
        'create_live_tempo_tap_point': 'Create Live Tempo Tap Point',
        'create_new_part': 'Create New Part',
        'create_pitch_a': 'Create A',
        'create_pitch_b': 'Create B',
        'create_pitch_c': 'Create C',
        'create_pitch_d': 'Create D',
        'create_pitch_e': 'Create E',
        'create_pitch_f': 'Create F',
        'create_pitch_g': 'Create G',
        'create_title_page': 'Title Page',
        'cross_stave_move_down': 'Move Down a Staff',
        'cross_stave_move_up': 'Move Up a Staff',
        'cross_stave_reset': 'Move to Original Staff',
        'custom_articulation1': 'Custom Articulation 1',
        'custom_articulation2': 'Custom Articulation 2',
        'custom_articulation3': 'Custom Articulation 3',
        'cut': 'Cut',
    },
    d: {
        'decrease_instrument_stave_size': 'Decrease Instrument Staff Size',
        'decrease_spacing_a_lot': 'Decrease Spacing a Lot',
        'decrease_spacing': 'Decrease Spacing',
        'default_positions': 'Default Positions',
        'delete_bar': 'Delete Bar',
        'delete_current_part_or_subset': 'Delete current part or subset',
        'delete_part': 'Delete Part',
        'delete': 'Delete',
        'document_setup': 'Document Setup',
        'doit': 'Doit',
        'double_dot': 'Double dot',
        'double_flat': 'Double flat',
        'double_sharp': 'Double sharp',
        'double_whole_note': 'Double whole note (breve)',
        'downbow': 'Downbow',
        'duplet': 'Duplet',
    },
    e: {
        'edit_all_fonts': 'Edit All Fonts',
        'edit_arrange_styles': 'Edit Arrange Styles',
        'edit_chord_diagram': 'Edit Chord Diagram',
        'edit_chord_symbols': 'Edit Chord Symbols',
        'edit_hitpoints': 'Hit points',
        'edit_instruments': 'Edit Instruments',
        'edit_lines': 'Edit Lines',
        'edit_noteheads': 'Notehead type gallery',
        'edit_plugins': 'Edit Plug-ins',
        'edit_staves_in_part': 'Edit Staves in Part',
        'edit_symbols': 'Edit Symbols',
        'edit_text_styles': 'Edit Text Styles',
        'edit_text': 'Edit Text',
        'edit_worksheets': 'Edit Worksheets',
        'end_beam': 'End beam',
        'end_line': 'End line',
        'end_slur': 'End slur',
        'engraving_rules': 'Engraving Rules',
        'equivalent_chord_text': 'Equivalent Chord Text',
        'exit_program': 'Exit',
        'export_as_audio': 'Export Audio',
        'export_as_graphic': 'Export Graphics',
        'export_as_manuscript_paper': 'Export Manuscript Paper',
        'export_as_midi': 'Export MIDI File',
        'export_as_musicxml': 'Export MusicXML',
        'export_as_older_version': 'Export Previous Sibelius Version',
        'export_as_pdf': 'Export PDF',
        'export_as_sib_student': 'Export Sibelius Student file',
        'export_as_video': 'Export Video File',
        'export_house_style': 'Export House Style',
        'extend_selection_down': 'Extend Selection Down',
        'extend_selection_left': 'Extend Selection Left',
        'extend_selection_right': 'Extend Selection Right',
        'extend_selection_to_bottom_staff': 'Extend Selection to Bottom Staff',
        'extend_selection_to_end_of_bar': 'Extend Selection to End of Bar',
        'extend_selection_to_start_of_bar': 'Extend Selection to Start of Bar',
        'extend_selection_to_top_of_staff': 'Extend Selection to Top of Staff',
        'extend_selection_up': 'Extend Selection Up',
        'extract_parts': 'Extract Parts',
    },
    f: {
        'fall': 'Fall',
        'fast_forward': 'Fast-forward',
        'feathered_beam_accel': 'Feathered beam accel.',
        'feathered_beam_rit': 'Feathered beam rit.',
        'find_next_collision': 'Find Next Collision',
        'find_next_comment': 'Find Next Comment',
        'find_next': 'Find Next',
        'find_previous_collision': 'Find Previous Collision',
        'find_previous_comment': 'Find Previous Comment',
        'find': 'Find',
        'flat': 'Flat',
        'flexitime_input': 'Flexi-time Input',
        'flexitime_options': 'Flexi-time Options',
        'flip': 'Flip',
        'focus_on_staves': 'Focus on Staves',
        'freeze_magnetic_layout_positions': 'Freeze Magnetic Layout Positions',
        'fretboard_window': 'Fretboard',
        'full_screen': 'Full Screen',
    },
    filter: {
        'filter_2nd_note_for_deletion': 'Filter 2nd from Top (For Deletion)',
        'filter_2nd_note': '2nd from Top',
        'filter_2nd_or_single_note_for_deletion': 'Filter 2nd Note or Single Notes (For Deletion)',
        'filter_2nd_pr_single_note': 'Filter 2nd Note or Single Notes (For Copying)',
        'filter_3rd_note_for_deletion': 'Filter 3rd from Top (For Deletion)',
        'filter_3rd_note': '3rd from Top',
        'filter_3rd_or_single_note_for_deletion': 'Filter 3rd Note or Single Notes (For Deletion)',
        'filter_3rd_or_single_note': 'Filter 3rd Note or Single Notes (For Copying)',
        'filter_all_barlines': 'Filter All Barlines',
        'filter_bar_numbers': 'Filter Bar Numbers',
        'filter_bottom_note_for_deletion': 'Filter Bottom Note (For Deletion)',
        'filter_bottom_note': 'Bottom Note',
        'filter_bottom_or_single_note_for_deletion': 'Filter Bottom Note or Single Notes (For Deletion)',
        'filter_bottom_or_single_note': 'Filter Bottom Note or Single Notes (For Copying)',
        'filter_chord_symbols': 'Filter Chord Symbols',
        'filter_comments': 'Filter Comment items',
        'filter_dynamics': 'Filter Dynamics',
        'filter_expression_text': 'Filter Expression Text',
        'filter_grace_notes': 'Filter Grace Notes',
        'filter_hairpins': 'Filter Hairpins',
        'filter_hidden_objects': 'Filter Hidden Objects',
        'filter_instrument_changes': 'Filter Instrument Changes',
        'filter_lyrics': 'Filter Lyrics',
        'filter_non_tied_notes': 'Filter notes that are not tied or that start a tie',
        'filter_nonspecial_barlines': 'Filter Non-Special Barlines',
        'filter_notes_and_chords': 'Filter Notes and Chords',
        'filter_page_numbers': 'Filter Page Numbers',
        'filter_pedal_lines': 'Filter Pedal Lines',
        'filter_player1': 'Filter Player 1 (For Deletion)',
        'filter_player2': 'Filter Player 2 (For Deletion)',
        'filter_rehearsal_marks': 'Filter Rehearsal Marks',
        'filter_repeat_bars': 'Filter Repeat Bars',
        'filter_rests': 'Filter Rests',
        'filter_slurs': 'Filter Slurs',
        'filter_special_barlines': 'Filter Special Barlines',
        'filter_staff_text': 'Filter Staff Text',
        'filter_symbols': 'Filter Symbols',
        'filter_system_text': 'Filter System Text',
        'filter_technique_text': 'Filter Technique Text',
        'filter_top_note_for_deletion': 'Filter Top Note (For Deletion)',
        'filter_top_note': 'Top Note',
        'filter_top_or_single_note_for_deletion': 'Filter Top Note or Single Notes (For Deletion)',
        'filter_top_or_single_note': 'Filter Top Note or Single Notes (For Copying)',
        'filter_tuplets': 'Filter Tuplets',
        'filter_voice1_only': 'Filter Voice 1 Only',
        'filter_voice1': 'Filter Voice 1',
        'filter_voice2_only': 'Filter Voice 2 Only',
        'filter_voice2': 'Filter Voice 2',
        'filter_voice3_only': 'Filter Voice 3 Only',
        'filter_voice3': 'Filter Voice 3',
        'filter_voice4_only': 'Filter Voice 4 Only',
        'filter_voice4': 'Filter Voice 4',
    },
    g: {
        'goto_bar': 'Go to Bar',
        'goto_page': 'Go to Page',
        'goto_playback_line': 'Go to Playback Line',
        'goto_selection_end': 'Go to selection end',
        'goto_selection_start': 'Go to selection start',
        'graphic_adjust_color': 'Adjust Colours',
        'graphic_change_link_source': 'Change Link Source',
        'graphic_flip_horizontal': 'Flip Horizontal',
        'graphic_flip_vertical': 'Flip Vertical',
        'graphic_rotate_180': 'Rotate 180 degrees',
        'graphic_rotate_270': 'Rotate 90 degrees CCW',
        'graphic_rotate_90': 'Rotate 90 degrees CW',
        'graphics': 'Graphic',
        'guitar_scale_diagram': 'Guitar Scale Diagram',
    },
    h: {
        'half_note': 'Half note (minim)',
        'harmonic_circle': 'Harmonic/Open',
        'hide_all_invisibles': 'Hide All Invisibles',
        'hide_all_panels': 'Hide Tool Windows',
        'hide_empty_staves': 'Hide Empty Staves',
        'hide_show_accidentals_toggle': 'Hide or show accidentals',
        'hide_show_toggle': 'Hide or Show',
    },
    i: {
        'ideas_window': 'Ideas',
        'import_file': 'Import',
        'import_house_style': 'Import House Style',
        'import_lyrics': 'Create Lyrics From Text File',
        'increase_instrument_stave_size': 'Increase Instrument Staff Size',
        'increase_spacing_a_lot': 'Increase Spacing a Lot',
        'increase_spacing': 'Increase Spacing',
        'input_notes': 'Input Notes',
        'install_plugins': 'Install Plug-ins',
        'instrument_and_stave_dialog': 'Instruments and Staves',
        'instrument_change': 'Instrument Change',
    },
    k: {
        'keep_bars_together': 'Keep Bars Together',
        'key_signature_dialog': 'Show Key Signature dialog',
        'key_signatures': 'Key Signature',
        'keyboard_window': 'Keyboard',
        'keypad_.': '\'.\' on keypad',
        'keypad_+': '\'+\' on keypad',
        'keypad_default_size': 'Reset keypad size',
        'keypad_enter': 'Enter on keypad',
        'keypad_first_layout': 'First keypad layout',
        'keypad_larger': 'Make keypad larger',
        'keypad_next_layout': 'Next keypad layout',
        'keypad_palette1': 'Common notes',
        'keypad_palette2': 'More notes',
        'keypad_palette3': 'Beams/tremolos',
        'keypad_palette4': 'Articulations',
        'keypad_palette5': 'Jazz Articulations',
        'keypad_palette6': 'Accidentals',
        'keypad_smaller': 'Make keypad smaller',
        'keypad': 'Keypad',
        'keypad0': '0 on keypad',
        'keypad1': '1 on keypad',
        'keypad2': '2 on keypad',
        'keypad3': '3 on keypad',
        'keypad4': '4 on keypad',
        'keypad5': '5 on keypad',
        'keypad6': '6 on keypad',
        'keypad7': '7 on keypad',
        'keypad8': '8 on keypad',
        'keypad9': '9 on keypad',
    },
    l: {
        'lines_dialog': 'Show Lines dialog (absolute) and Select Note in Next Voice',
        'lines': 'Line',
        'live_playback_velocities': 'Live Playback Velocities',
        'live_playback': 'Live Playback',
        'live_tempo_tap_points': 'Live Tempo Tap Points',
        'lock_format': 'Lock Format',
        'long': 'Long',
    },
    m: {
        'magnetic_layout_off': 'Turn off Magnetic Layout for item',
        'magnetic_layout_on': 'Turn on Magnetic Layout for item',
        'magnetic_layout_options': 'Magnetic Layout Options',
        'make_into_bar': 'Make Into Bar',
        'make_into_page': 'Make Into Page',
        'make_into_score_subset': 'Make into score subset',
        'make_into_system': 'Make Into System',
        'manuscript_language_reference': 'ManuScript Language Reference',
        'marcato': 'Marcato',
        'mid_beam': 'Middle of beam',
        'minimize_expand_ribbon': 'Minimize/Expand Ribbon',
        'minimize_window': 'Minimize Window',
        'mixer': 'Mixer',
        'move_down_chromatically': 'Move Down Chromatically',
        'move_instruments_down': 'Move Instruments Down',
        'move_instruments_up': 'Move Instruments Up',
        'move_object_down_a_lot': 'Move Object Down a Lot',
        'move_object_down': 'Move Object Down',
        'move_object_left_a_lot': 'Move Object Left a Lot',
        'move_object_left': 'Move Object Left',
        'move_object_right_a_lot': 'Move Object Right a Lot',
        'move_object_right': 'Move Object Right',
        'move_object_up_a_lot': 'Move Object Up a Lot',
        'move_object_up': 'Move Object Up',
        'move_playback_to_selection': 'Move Playback Line to Selection',
        'move_screen_left_a_bit': 'Move Screen Left a Bit',
        'move_screen_right_a_bit': 'Move Screen Right a Bit',
        'move_selection_to_playback': 'Move Selection to Playback Line',
        'move_staff_down_a_lot': 'Move Staff Down a Lot (absolute)',
        'move_staff_down_relative_a_lot': 'Move Staff Down a Lot (relative) and Select Note in Staff Below',
        'move_staff_down_relative': 'Move Staff Down (relative)',
        'move_staff_down_select_note_next_voice': 'Move Staff Down',
        'move_staff_up_a_lot': 'Move Staff Up a Lot (absolute)',
        'move_staff_up_relative_a_lot': 'Move Staff Up a Lot (relative) and Select Note in Staff Above',
        'move_staff_up_relative': 'Move Staff Up (relative)',
        'move_staff_up_select_note_previous_voice': 'Move Staff Up (absolute) and Select Note in Previous Voice',
        'move_up_chromatically': 'Move Up Chromatically',
    },
    n: {
        'natural_flat': 'Natural flat',
        'natural_sharp': 'Natural sharp',
        'natural': 'Natural',
        'nav_down': 'Move stave down (relative) and Select part of object below',
        'nav_up': 'Move stave up (relative) / Select part of object above',
        'navigator': 'Navigator',
        'new_file': 'New',
        'new_window': 'New Window',
        'next_part': 'Next Part',
        'next_window_tab': 'Select Next Tab',
        'no_beam': 'No beam',
        'nonuplet': 'Nonuplet',
        'note_spacing_rules': 'Note Spacing Rule',
        'notehead_0': 'Notehead 0',
        'notehead_1': 'Notehead 1',
        'notehead_2': 'Notehead 2',
        'notehead_3': 'Notehead 3',
        'notehead_4': 'Notehead 4',
        'notehead_5': 'Notehead 5',
        'notehead_6': 'Notehead 6',
        'notehead_7': 'Notehead 7',
        'notehead_8': 'Notehead 8',
        'notehead_9': 'Notehead 9',
        'noteheads': 'Edit Noteheads',
    },
    o: {
        'object_rulers': 'Object Rulers',
        'octuplet': 'Octopus',
        'open_file': 'Open',
        'optimize_staff_spacing': 'Optimize Staff Spacing',
        'ordering_move_back': 'Send Back',
        'ordering_move_forward': 'Bring Forward',
        'ordering_move_to_back': 'Send to Back',
        'ordering_move_to_front': 'Bring to Front',
        'ordering_reset_to_default': 'Reset to Default Order',
        'override_pitch_before_duration': 'Override pitch before duration',
    },
    p: {
        'page_bottom': 'Move bottom of page',
        'page_break': 'Page Break',
        'page_down_a_bit': 'Move page down a bit',
        'page_down': 'Move down full screen',
        'page_first': 'Move to first page',
        'page_last': 'Move to last page',
        'page_left': 'Move left full screen',
        'page_number_change': 'Page Number Change',
        'page_right': 'Move right full screen',
        'page_top': 'Move to top of page',
        'page_up_a_bit': 'Move page up a bit',
        'page_up': 'Move up full screen',
        'panorama_view': 'Panorama',
        'paste_as_cue': 'Paste as Cue',
        'paste': 'Paste',
        'pause': 'Fermata (pause)',
        'performance_interpretation': 'Performance',
        'play_from_selection': 'Play From Selection',
        'play_half_speed_extend_lines': 'Play at half-speed or snap line/lyric to previous note',
        'play_live_tempo': 'Live Tempo',
        'play/stop_or_extend_line': 'Play/Stop or snap line/lyric to next  note',
        'play/stop': 'Play/Stop',
        'playback_all_notes_off': 'All Notes Off',
        'playback_backward_one_frame': 'Move backward a single frame',
        'playback_devices': 'Playback Devices',
        'playback_dictionary': 'Playback Dictionary',
        'playback_forward_one_frame': 'Move forward a single frame',
        'playback_line_to_end': 'Move Playback Line to End',
        'playback_line_to_start': 'Move Playback Line to Start',
        'playback_stop': 'Stop',
        'plop': 'Plop',
        'plus': 'Plus/Closed',
        'prebend_note': 'Pre-bend note',
        'preferences': 'Preferences',
        'previous_part': 'Previous Part',
        'previous_window_tab': 'Select Previous Tab',
        'print_all_parts': 'Print All Parts',
        'print_copies_of_parts': 'Print Copies of Parts',
        'print_dialog': 'OS Print Dialog',
        'print': 'Print',
        'publish_to_score_exchange': 'Publish to Score Exchange',
    },
    q: {
        'quadruplet': 'Quadruplet',
        'quarter_flat': 'Quarter flat',
        'quarter_note': 'Quarter note (crotchet)',
        'quarter_sharp': 'Quarter sharp',
        'quick_start': 'Quick Start',
        'quintuplet': 'Quintuplet',
    },
    r: {
        'reapply_color': 'Reapply Color',
        'rebeam': 'Re-beam',
        'record_live_tempo': 'Record Live Tempo',
        'record_with_audioscore': 'Record with AudioScore',
        'redo_dialog': 'Redo History',
        'redo': 'Redo',
        'remove_accidental': 'Remove accidentals',
        'remove_articulation': 'Remove articulations',
        'remove_staves': 'Remove Staves',
        'repeat_2_bars': '2 bar Repeat Bar',
        'repeat_4_bars': '4 bar Repeat Bar',
        'repeat_bar': 'Repeat Bar',
        'repeat_interpretation': 'Repeats',
        'repeat': 'Repeat',
        'repitch': 'Re-input Pitches',
        'replay': 'Replay',
        'reset_beam_groups': 'Reset Beam Groups',
        'reset_design': 'Reset Design',
        'reset_magnetic_layout': 'Use default Magnetic Layout settings',
        'reset_note_spacing': 'Reset Note Spacing',
        'reset_position': 'Reset Position',
        'reset_space_above_staff': 'Reset Space Above Staff',
        'reset_space_below_staff': 'Reset Space Below Staff',
        'reset_stems_and_beam_positions': 'Reset Stems and Beam Positions',
        'reset_tab_fingering': 'Reset Guitar Tab Fingering',
        'reset_to_score_design': 'Reset to Score Design',
        'reset_to_score_position': 'Reset to Score Position',
        'respell_chord_text': 'Respell Chord Text',
        'respell': 'Respell Accidental/Edit Text',
        'rest': 'Rest',
        'restart_rehearsal_marks': 'Restart Rehearsal Marks',
        'revoice_chord_diagram': 'Revoice Chord Diagram',
        'rewind': 'Rewind',
        'rhythm_dot': 'Rhythm dot',
    },
    'sa-sh': {
        'save_all': 'Save All',
        'save_as_worksheet': 'Add to Worksheet Creator',
        'save_as': 'Save As',
        'save': 'Save',
        'scan_with_photoscore': 'Scan with PhotoScore',
        'scoop': 'Scoop',
        'score_info': 'Score Info',
        'scrub_backwards': 'Scrub Backward',
        'scrub_forward': 'Scrub Forward',
        'section_end': 'Section End',
        'select_all': 'Select All',
        'select_bars': 'Select Bars',
        'select_graphic': 'Select Graphic',
        'select_more': 'Select More',
        'select_next_fragment': 'Select Next Part of Object',
        'select_next_note': 'Move Object Right/Select Next Note',
        'select_next_object': 'Select Next Object',
        'select_next_system_object': 'Select Next System Object',
        'select_none': 'Select None',
        'select_previous_fragment': 'Select Previous Part of Object',
        'select_previous_note': 'Move Object Left/Select Previous Note',
        'select_previous_object': 'Select Previous Object',
        'select_previous_system_object': 'Select Previous System Object',
        'select_system_passage': 'Select System Passage',
        'selection_rulers': 'Selection Rulers',
        'septuplet': 'Septuplet',
        'sextuplet': 'Sextuplet',
        'sharp': 'Sharp',
        'show_annotations': 'View Annotations',
        'show_attachment_lines': 'Attachment Lines',
        'show_bar_numbers': 'Staff Names and Bar Numbers',
        'show_comments': 'View Comments',
        'show_differences_between_versions': 'View Differences Between Versions',
        'show_differences_in_parts': 'Differences In Parts',
        'show_empty_staves': 'Show Empty Staves',
        'show_handles': 'Handles',
        'show_hidden_objects': 'Hidden Objects',
        'show_highlights': 'Highlights',
        'show_in_all': 'Show in All',
        'show_in_parts': 'Show in Parts',
        'show_in_score': 'Show in Score',
        'show_inspector': 'Inspector',
        'show_layout_marks': 'Layout Marks',
        'show_magnetic_layout_collisions': 'Magnetic Layout Collisions',
        'show_magnetic_layout_groups': 'View Magnetic Layout Groups',
        'show_magnetic_layout_original_positions': 'View Magnetic Layout Original Positions',
        'show_page_margins': 'Page Margins',
        'show_playback_line': 'Playback Line',
        'show_plugin_trace': 'Show Plugin Trace Window',
        'show_replay_marker': 'Replay Line',
    },
    'si-sy': {
        'sibelius_help': 'Sibelius Help',
        'sibelius_tutorials': 'Sibelius Tutorials',
        'single_pages_horizontally': 'Single Pages Horizontally',
        'single_pages_vertically': 'Single Pages Vertically',
        'slide_notes_or_rests_left': 'Slide notes or rests left',
        'slide_notes_or_rests_right': 'Slide notes or rests right',
        'slide': 'Slide',
        'snap_line_next_note': 'Snap line/lyric to next note',
        'special_page_break': 'Special Page Break',
        'split_multirest': 'Split Multirest',
        'split_system': 'Split System',
        'spreads_horizontally': 'Spreads Horizontally',
        'spreads_vertically': 'Spreads Vertically',
        'squarepause': 'Long fermata',
        'staccatissimo': 'Staccatissimo',
        'staccato': 'Staccato',
        'staff_rulers': 'Staff Rulers',
        'start_beam': 'Start beam',
        'start_sub_beam': 'Start secondary beam',
        'stemlet': 'Stemlet',
        'subbracket': 'Sub-bracket',
        'suppress_auto_cautionary_accidental': 'Suppress auto cautionary accidental',
        'swap_voices_1_and_2': 'Swap Voices 1 and 2',
        'swap_voices_1_and_3': 'Swap Voices 1 and 3',
        'swap_voices_1_and_4': 'Swap Voices 1 and 4',
        'swap_voices_2_and_3': 'Swap Voices 2 and 3',
        'swap_voices_2_and_4': 'Swap Voices 2 and 4',
        'swap_voices_3_and_4': 'Swap Voices 3 and 4',
        'switch_between_full_score_and_parts': 'Switch Between Full Score and Part',
        'symbols_dialog': 'Show symbols dialog',
        'symbols': 'Symbol',
        'system_break_respell_edit_text': 'System Break/Respell Accidental/Edit Text',
        'system_break': 'System Break',
        'system_object_positions': 'System Object Positions',
    },
    t: {
        'tab_fret_number0': 'Fret number 0 on tab',
        'tenuto': 'Tenuto',
        'text_styles': 'Text Style',
        'three_quarter_flat': 'Three quarter flat',
        'three_quarter_sharp': 'Three quarter sharp',
        'tie_into': 'Tie Into',
        'tie': 'Tie',
        'tile_horizontally': 'Tile Horizontally',
        'tile_vertically': 'Tile Vertically',
        'time_signature_dialog': 'Show Time Signature dialog',
        'time_signatures': 'Time Signature',
        'timecode_and_duration': 'Timecode and Duration',
        'timeline': 'Timeline',
        'toggle_auto_optimize': 'Switch Auto-Optimize on / off',
        'toggle_cue_size': 'Cue size (on/off)',
        'toggle_loop_mode': 'Loop',
        'toggle_lv_tie': 'Toggle L.V. tie',
        'toggle_magnetic_layout': 'Switch magnetic layout on / off',
        'toggle_notes/rests': 'Toggle Notes/Rests',
        'toggle_review_mode': 'Toggle Review Mode',
        'toggle_sticky_tuplet': 'Toggle sticky tuplet',
        'tranposing_score': 'Transposing Score',
        'transform_live_playback': 'Transform Live Playback',
        'transport': 'Transport',
        'transpose': 'Transpose',
        'tremolo_with_next_note': 'Tremolo with next note',
        'tripause': 'Short fermata',
        'triple_dot': 'Triple dot',
        'triplet': 'Triplet',
        'tuplet': 'Tuplet',
        'turn_note_into_grace_note': 'Turn note into gracenote',
    },
    u: {
        'undo_dialog': 'Undo History',
        'undo': 'Undo',
        'unlock_format': 'Unlock Format',
        'upbow': 'Upbow',
        'use_multirests': 'Use Multirests',
    },
    v: {
        'versions_edit': 'Edit Versions',
        'versions_export_current': 'Export Current Version',
        'versions_export_log': 'Export Version Log',
        'versions_make_current': 'Make Current Version',
        'versions_save': 'Save Version',
        'versions_show_next': 'Show Next Version',
        'versions_show_previous': 'Show Previous Version',
        'video_double_size': 'Double Size',
        'video_fullscreen': 'Full Screen',
        'video_half_size': 'Half Size',
        'video_normal_size': 'Full Size',
        'video_window': 'Video',
        'view_live_tempo': 'View Live Tempo',
        'voice_all': 'Voice All',
        'voice1': 'Voice 1',
        'voice2': 'Voice 2',
        'voice3': 'Voice 3',
        'voice4': 'Voice 4',
    },
    w: {
        'wedge': 'Wedge',
        'whats_new': 'What\'s New',
        'whole_note': 'Whole note (semibreve)',
        'worksheet_creator': 'Worksheet Creator',
    },
    z: {
        'zoom_100%': 'Zoom 100%',
        'zoom_12.5%': 'Zoom 12.5%',
        'zoom_125%': 'Zoom 125%',
        'zoom_150%': 'Zoom 150%',
        'zoom_200%': 'Zoom 200%',
        'zoom_25%': 'Zoom 25%',
        'zoom_300%': 'Zoom 300%',
        'zoom_37.5%': 'Zoom 37.5%',
        'zoom_400%': 'Zoom 400%',
        'zoom_50%': 'Zoom 50%',
        'zoom_62.5%': 'Zoom 62.5%',
        'zoom_75%': 'Zoom 75%',
        'zoom_800%': 'Zoom 800%',
        'zoom_87.5%': 'Zoom 87.5%',
        'zoom_actual_size': 'Zoom to actual size',
        'zoom_edit': 'Zoom',
        'zoom_in': 'Zoom In',
        'zoom_out': 'Zoom Out',
        'zoom_to_fit_page': 'Zoom Window',
        'zoom_to_fit_two_pages': 'Zoom to fit 2 pages',
        'zoom_to_fit': 'Zoom to fit page',
        'zoom_to_page_height': 'Zoom to page height',
        'zoom_to_page_width': 'Zoom to fit page width',
        'zoom_to_system_width': 'Zoom to system width',
    }
};